[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lssvr"
requires-python = ">=3.8"
dependencies=[
"numpy>=1.19.2",
"scikit-learn>=0.23.2",
"scipy>=1.5.2"
]

